2024-05-17 13:05:24,593:INFO:Running command: python distinguisher.py +distinguisher=llama3 ++distinguisher.log_suffix=05_17_llama_entropy_6_hard_attack ++distinguisher.entropy='"6"' ++distinguisher.output_1='"1"' ++distinguisher.attack_id_1='"3"' ++distinguisher.output_2='"2"' ++distinguisher.attack_id_2='"4"' 
2024-05-17 13:05:24,593:INFO:Saving results to ./results/stationary_distribution/robustness_analysis/entropy_6/distinguisher_results/1_3-2_4_05_17_llama_entropy_6_hard_attack.log
2024-05-17 13:05:29,234:ERROR:Command failed with error: None
2024-05-17 13:05:29,235:INFO:[(None, None)]
Command succeeded: python distinguisher.py +distinguisher=llama3 ++distinguisher.log_suffix=05_17_llama_entropy_6_hard_attack ++distinguisher.entropy='"6"' ++distinguisher.output_1='"1"' ++distinguisher.attack_id_1='"3"' ++distinguisher.output_2='"2"' ++distinguisher.attack_id_2='"4"' 
Output:
None
