[2024-02-21 22:29:39,827][datasets][INFO] - PyTorch version 2.1.2 available.
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/modeling_utils.py:4193: FutureWarning: `_is_quantized_training_enabled` is going to be deprecated in transformers 4.39.0. Please use `model.hf_quantizer.is_trainable` instead
  warnings.warn(
[2024-02-21 22:29:46,721][accelerate.utils.modeling][INFO] - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
[2024-02-21 22:30:19,419][accelerate.utils.modeling][INFO] - We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:07<00:21,  7.17s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:14<00:14,  7.40s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:20<00:06,  6.66s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:23<00:00,  5.03s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:23<00:00,  5.76s/it]
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
  0%|          | 0/500 [00:00<?, ?it/s][2024-02-21 22:30:43,807][__main__][INFO] - Mutating watermarked text...
[2024-02-21 22:30:50,206][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:50,333][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:50,460][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:50,585][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:50,711][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:50,711][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:50,712][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:50,712][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:50,712][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:50,713][__main__][INFO] - Low quality mutation. Retrying step...
  0%|          | 1/500 [00:06<57:26,  6.91s/it][2024-02-21 22:30:50,713][__main__][INFO] - Mutating watermarked text...
[2024-02-21 22:30:50,840][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:50,966][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:51,093][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:51,218][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:51,344][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:51,344][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:51,344][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:51,345][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:51,345][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:51,346][__main__][INFO] - Low quality mutation. Retrying step...
  0%|          | 2/500 [00:07<26:41,  3.22s/it][2024-02-21 22:30:51,346][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:51,470][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:51,595][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:51,720][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:51,846][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:51,973][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:51,973][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:51,973][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:51,973][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:51,973][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:51,974][__main__][INFO] - Low quality mutation. Retrying step...
  1%|          | 3/500 [00:08<16:51,  2.03s/it][2024-02-21 22:30:51,974][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,100][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,225][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,350][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,476][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,603][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:52,603][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:52,603][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:52,603][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:52,603][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:52,604][__main__][INFO] - Low quality mutation. Retrying step...
  1%|          | 4/500 [00:08<12:14,  1.48s/it][2024-02-21 22:30:52,604][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,730][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,857][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:52,983][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,108][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,232][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:53,233][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:53,233][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:53,233][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:53,233][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:53,234][__main__][INFO] - Low quality mutation. Retrying step...
  1%|          | 5/500 [00:09<09:40,  1.17s/it][2024-02-21 22:30:53,234][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,361][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,485][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,611][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,737][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,864][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:53,864][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:53,864][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:53,864][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:53,864][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:53,865][__main__][INFO] - Low quality mutation. Retrying step...
  1%|          | 6/500 [00:10<08:08,  1.01it/s][2024-02-21 22:30:53,865][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:53,991][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,116][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,241][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,367][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,493][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:54,493][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:54,494][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:54,494][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:54,494][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:54,495][__main__][INFO] - Low quality mutation. Retrying step...
  1%|▏         | 7/500 [00:10<07:09,  1.15it/s][2024-02-21 22:30:54,495][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,621][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,746][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,872][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:54,997][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:55,123][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:55,123][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:55,123][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:55,123][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:55,123][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:55,124][__main__][INFO] - Low quality mutation. Retrying step...
  2%|▏         | 8/500 [00:11<06:30,  1.26it/s][2024-02-21 22:30:55,124][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:55,249][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:55,376][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:55,501][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:55,628][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:55,755][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:55,755][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:55,755][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:55,755][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:55,755][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:55,756][__main__][INFO] - Low quality mutation. Retrying step...
  2%|▏         | 9/500 [00:11<06:05,  1.34it/s][2024-02-21 22:30:55,756][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:55,881][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,008][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,135][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,262][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,389][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:56,389][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:56,389][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:56,389][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:56,389][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:56,390][__main__][INFO] - Low quality mutation. Retrying step...
  2%|▏         | 10/500 [00:12<05:47,  1.41it/s][2024-02-21 22:30:56,390][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,515][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,642][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,769][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:56,895][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,022][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:57,022][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:57,022][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:57,022][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:57,022][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:57,023][__main__][INFO] - Low quality mutation. Retrying step...
  2%|▏         | 11/500 [00:13<05:35,  1.46it/s][2024-02-21 22:30:57,023][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,150][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,277][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,404][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,529][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,653][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:57,653][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:57,653][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:57,654][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:57,654][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:57,654][__main__][INFO] - Low quality mutation. Retrying step...
  2%|▏         | 12/500 [00:13<05:26,  1.49it/s][2024-02-21 22:30:57,655][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,780][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:57,905][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,032][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,160][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,287][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:58,287][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:58,287][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:58,287][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:58,287][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:58,288][__main__][INFO] - Low quality mutation. Retrying step...
  3%|▎         | 13/500 [00:14<05:20,  1.52it/s][2024-02-21 22:30:58,288][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,415][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,542][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,668][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,793][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:58,918][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:58,918][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:58,919][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:58,919][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:58,919][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:58,919][__main__][INFO] - Low quality mutation. Retrying step...
  3%|▎         | 14/500 [00:15<05:16,  1.54it/s][2024-02-21 22:30:58,920][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,044][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,169][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,295][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,421][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,548][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:30:59,548][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:30:59,548][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:30:59,548][__main__][INFO] - Mutated text: None
[2024-02-21 22:30:59,548][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:30:59,549][__main__][INFO] - Low quality mutation. Retrying step...
  3%|▎         | 15/500 [00:15<05:12,  1.55it/s][2024-02-21 22:30:59,549][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,676][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,803][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:30:59,928][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,053][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,178][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:00,178][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:00,178][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:00,178][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:00,178][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:00,179][__main__][INFO] - Low quality mutation. Retrying step...
  3%|▎         | 16/500 [00:16<05:09,  1.56it/s][2024-02-21 22:31:00,179][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,306][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,431][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,558][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,685][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,812][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:00,812][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:00,812][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:00,812][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:00,812][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:00,813][__main__][INFO] - Low quality mutation. Retrying step...
  3%|▎         | 17/500 [00:17<05:08,  1.57it/s][2024-02-21 22:31:00,813][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:00,939][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,064][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,191][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,318][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,443][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:01,443][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:01,443][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:01,444][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:01,444][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:01,444][__main__][INFO] - Low quality mutation. Retrying step...
  4%|▎         | 18/500 [00:17<05:06,  1.57it/s][2024-02-21 22:31:01,445][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,572][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,697][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,824][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:01,949][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,075][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:02,075][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:02,075][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:02,075][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:02,075][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:02,076][__main__][INFO] - Low quality mutation. Retrying step...
  4%|▍         | 19/500 [00:18<05:05,  1.58it/s][2024-02-21 22:31:02,076][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,203][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,330][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,455][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,582][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,709][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:02,709][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:02,709][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:02,709][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:02,709][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:02,711][__main__][INFO] - Low quality mutation. Retrying step...
  4%|▍         | 20/500 [00:18<05:04,  1.58it/s][2024-02-21 22:31:02,711][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,838][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:02,964][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,089][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,214][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,341][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:03,341][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:03,341][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:03,341][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:03,341][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:03,342][__main__][INFO] - Low quality mutation. Retrying step...
  4%|▍         | 21/500 [00:19<05:03,  1.58it/s][2024-02-21 22:31:03,342][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,469][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,594][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,720][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,847][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:03,975][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:03,975][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:03,975][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:03,975][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:03,975][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:03,977][__main__][INFO] - Low quality mutation. Retrying step...
  4%|▍         | 22/500 [00:20<05:03,  1.58it/s][2024-02-21 22:31:03,977][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,104][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,231][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,358][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,485][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,612][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:04,612][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:04,612][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:04,612][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:04,612][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:04,613][__main__][INFO] - Low quality mutation. Retrying step...
  5%|▍         | 23/500 [00:20<05:02,  1.58it/s][2024-02-21 22:31:04,613][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,739][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,866][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:04,991][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:05,116][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:05,242][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:05,243][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:05,243][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:05,243][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:05,243][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:05,244][__main__][INFO] - Low quality mutation. Retrying step...
  5%|▍         | 24/500 [00:21<05:01,  1.58it/s][2024-02-21 22:31:05,244][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:05,370][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:05,495][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:05,622][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:05,749][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:05,874][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:05,874][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:05,874][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:05,874][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:05,874][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:05,875][__main__][INFO] - Low quality mutation. Retrying step...
  5%|▌         | 25/500 [00:22<05:00,  1.58it/s][2024-02-21 22:31:05,875][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,000][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,125][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,251][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,377][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,504][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:06,504][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:06,504][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:06,504][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:06,504][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:06,505][__main__][INFO] - Low quality mutation. Retrying step...
  5%|▌         | 26/500 [00:22<04:59,  1.58it/s][2024-02-21 22:31:06,505][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,632][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,756][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:06,883][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,010][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,136][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:07,136][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:07,136][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:07,136][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:07,136][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:07,137][__main__][INFO] - Low quality mutation. Retrying step...
  5%|▌         | 27/500 [00:23<04:58,  1.58it/s][2024-02-21 22:31:07,137][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,264][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,389][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,514][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,641][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,767][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:07,768][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:07,768][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:07,768][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:07,768][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:07,769][__main__][INFO] - Low quality mutation. Retrying step...
  6%|▌         | 28/500 [00:23<04:58,  1.58it/s][2024-02-21 22:31:07,769][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:07,893][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,020][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,147][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,272][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,397][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:08,397][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:08,398][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:08,398][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:08,398][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:08,398][__main__][INFO] - Low quality mutation. Retrying step...
  6%|▌         | 29/500 [00:24<04:57,  1.58it/s][2024-02-21 22:31:08,399][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,525][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,652][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,778][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:08,905][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,032][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:09,032][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:09,032][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:09,032][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:09,032][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:09,033][__main__][INFO] - Low quality mutation. Retrying step...
  6%|▌         | 30/500 [00:25<04:57,  1.58it/s][2024-02-21 22:31:09,033][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,159][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,286][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,412][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,537][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,664][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:09,664][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:09,664][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:09,664][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:09,664][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:09,665][__main__][INFO] - Low quality mutation. Retrying step...
  6%|▌         | 31/500 [00:25<04:56,  1.58it/s][2024-02-21 22:31:09,665][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,792][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:09,919][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,045][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,170][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,297][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:10,297][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:10,297][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:10,297][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:10,297][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:10,298][__main__][INFO] - Low quality mutation. Retrying step...
  6%|▋         | 32/500 [00:26<04:55,  1.58it/s][2024-02-21 22:31:10,298][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,425][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,552][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,677][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,805][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:10,932][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:10,932][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:10,932][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:10,932][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:10,932][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:10,933][__main__][INFO] - Low quality mutation. Retrying step...
  7%|▋         | 33/500 [00:27<04:55,  1.58it/s][2024-02-21 22:31:10,933][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,058][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,185][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,312][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,438][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,565][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:11,565][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:11,565][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:11,565][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:11,565][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:11,566][__main__][INFO] - Low quality mutation. Retrying step...
  7%|▋         | 34/500 [00:27<04:55,  1.58it/s][2024-02-21 22:31:11,566][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,693][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,818][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:11,943][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,070][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,197][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:12,197][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:12,197][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:12,197][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:12,197][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:12,198][__main__][INFO] - Low quality mutation. Retrying step...
  7%|▋         | 35/500 [00:28<04:54,  1.58it/s][2024-02-21 22:31:12,198][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,323][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,450][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,576][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,703][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,828][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:12,828][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:12,829][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:12,829][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:12,829][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:12,829][__main__][INFO] - Low quality mutation. Retrying step...
  7%|▋         | 36/500 [00:29<04:53,  1.58it/s][2024-02-21 22:31:12,830][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:12,955][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,080][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,206][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,333][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,460][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:13,460][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:13,460][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:13,460][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:13,460][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:13,461][__main__][INFO] - Low quality mutation. Retrying step...
  7%|▋         | 37/500 [00:29<04:52,  1.58it/s][2024-02-21 22:31:13,461][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,588][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,713][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,840][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:13,967][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,093][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:14,093][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:14,094][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:14,094][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:14,094][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:14,094][__main__][INFO] - Low quality mutation. Retrying step...
  8%|▊         | 38/500 [00:30<04:52,  1.58it/s][2024-02-21 22:31:14,095][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,221][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,346][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,473][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,598][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,723][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:14,723][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:14,723][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:14,723][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:14,723][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:14,724][__main__][INFO] - Low quality mutation. Retrying step...
  8%|▊         | 39/500 [00:30<04:51,  1.58it/s][2024-02-21 22:31:14,724][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,849][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:14,976][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,101][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,227][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,352][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:15,352][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:15,352][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:15,352][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:15,352][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:15,353][__main__][INFO] - Low quality mutation. Retrying step...
  8%|▊         | 40/500 [00:31<04:50,  1.59it/s][2024-02-21 22:31:15,353][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,480][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,607][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,734][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,859][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:15,984][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:15,985][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:15,985][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:15,985][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:15,985][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:15,986][__main__][INFO] - Low quality mutation. Retrying step...
  8%|▊         | 41/500 [00:32<04:49,  1.58it/s][2024-02-21 22:31:15,986][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,111][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,238][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,365][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,490][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,616][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:16,616][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:16,616][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:16,616][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:16,616][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:16,617][__main__][INFO] - Low quality mutation. Retrying step...
  8%|▊         | 42/500 [00:32<04:49,  1.58it/s][2024-02-21 22:31:16,617][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,742][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,869][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:16,996][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:17,123][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:17,250][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:17,250][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:17,250][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:17,251][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:17,251][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:17,252][__main__][INFO] - Low quality mutation. Retrying step...
  9%|▊         | 43/500 [00:33<04:49,  1.58it/s][2024-02-21 22:31:17,252][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:17,379][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:17,506][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:17,632][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:17,759][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:17,886][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:17,886][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:17,886][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:17,886][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:17,886][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:17,887][__main__][INFO] - Low quality mutation. Retrying step...
  9%|▉         | 44/500 [00:34<04:48,  1.58it/s][2024-02-21 22:31:17,887][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,013][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,138][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,266][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,391][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,518][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:18,519][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:18,519][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:18,519][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:18,519][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:18,520][__main__][INFO] - Low quality mutation. Retrying step...
  9%|▉         | 45/500 [00:34<04:48,  1.58it/s][2024-02-21 22:31:18,520][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,645][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,771][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:18,898][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,026][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,153][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:19,153][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:19,154][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:19,154][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:19,154][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:19,155][__main__][INFO] - Low quality mutation. Retrying step...
  9%|▉         | 46/500 [00:35<04:47,  1.58it/s][2024-02-21 22:31:19,155][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,280][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,407][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,535][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,660][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,788][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:19,788][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:19,788][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:19,788][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:19,788][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:19,789][__main__][INFO] - Low quality mutation. Retrying step...
  9%|▉         | 47/500 [00:35<04:47,  1.58it/s][2024-02-21 22:31:19,789][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:19,916][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,043][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,169][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,295][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,422][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:20,422][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:20,422][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:20,422][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:20,422][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:20,423][__main__][INFO] - Low quality mutation. Retrying step...
 10%|▉         | 48/500 [00:36<04:46,  1.58it/s][2024-02-21 22:31:20,423][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,549][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,677][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,804][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:20,929][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,055][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:21,055][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:21,055][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:21,055][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:21,055][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:21,056][__main__][INFO] - Low quality mutation. Retrying step...
 10%|▉         | 49/500 [00:37<04:45,  1.58it/s][2024-02-21 22:31:21,056][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,183][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,310][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,436][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,563][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,690][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:21,690][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:21,690][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:21,690][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:21,690][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:21,691][__main__][INFO] - Low quality mutation. Retrying step...
 10%|█         | 50/500 [00:37<04:45,  1.58it/s][2024-02-21 22:31:21,691][__main__][INFO] - Mutating watermarked text...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,819][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:21,944][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:22,072][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:22,197][mutate][INFO] - Failed to produce a valid generation, trying again...
/home/borito1907/anaconda3/envs/watermark/lib/python3.11/site-packages/transformers/pipelines/base.py:1157: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
[2024-02-21 22:31:22,324][mutate][INFO] - Failed to produce a valid generation, trying again...
[2024-02-21 22:31:22,325][mutate][INFO] - Failed to produce a valid generation after 5 tries.
[2024-02-21 22:31:22,325][mutate][INFO] - Traceback (most recent call last):
  File "/home/borito1907/impossibility-watermark/mutate.py", line 174, in mutate
    mutated_text = self.creatively_alter_sentence(text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/borito1907/impossibility-watermark/mutate.py", line 143, in creatively_alter_sentence
    rephrased_sentence = creative_sentences[0]
                         ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

[2024-02-21 22:31:22,325][__main__][INFO] - Mutated text: None
[2024-02-21 22:31:22,325][__main__][INFO] - Mutation failed to preserve text length requirement...
Data appended to ./eval/results/attack_2024-02-21.22.30.43.csv
[2024-02-21 22:31:22,325][__main__][INFO] - Low quality mutation. Retrying step...
 10%|█         | 51/500 [00:38<04:44,  1.58it/s][2024-02-21 22:31:22,326][__main__][ERROR] - Mixing patience exceeded. Attack failed...
 10%|█         | 51/500 [00:38<05:39,  1.32it/s]
[2024-02-21 22:31:22,326][__main__][INFO] - Prompt: Provide a straightforward description of the Eiffel Tower's physical features without using complex or elaborate language.
[2024-02-21 22:31:22,326][__main__][INFO] - Attacked Response: None
